const EXERCISES = [
  // CHEST
  { id: 'e001', name: 'Flat Barbell Bench Press', muscle: 'Chest', category: 'Compound', equipment: 'Barbell' },
  { id: 'e002', name: 'Incline Barbell Bench Press', muscle: 'Chest', category: 'Compound', equipment: 'Barbell' },
  { id: 'e003', name: 'Decline Barbell Bench Press', muscle: 'Chest', category: 'Compound', equipment: 'Barbell' },
  { id: 'e004', name: 'Flat Dumbbell Bench Press', muscle: 'Chest', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e005', name: 'Incline Dumbbell Press', muscle: 'Chest', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e006', name: 'Decline Dumbbell Press', muscle: 'Chest', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e007', name: 'Dumbbell Fly', muscle: 'Chest', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e008', name: 'Incline Dumbbell Fly', muscle: 'Chest', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e009', name: 'Cable Crossover', muscle: 'Chest', category: 'Isolation', equipment: 'Cable' },
  { id: 'e010', name: 'High-to-Low Cable Fly', muscle: 'Chest', category: 'Isolation', equipment: 'Cable' },
  { id: 'e011', name: 'Low-to-High Cable Fly', muscle: 'Chest', category: 'Isolation', equipment: 'Cable' },
  { id: 'e012', name: 'Push-Up', muscle: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e013', name: 'Wide Push-Up', muscle: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e014', name: 'Diamond Push-Up', muscle: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e015', name: 'Chest Dip', muscle: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e016', name: 'Machine Chest Press', muscle: 'Chest', category: 'Compound', equipment: 'Machine' },
  { id: 'e017', name: 'Pec Deck Machine', muscle: 'Chest', category: 'Isolation', equipment: 'Machine' },
  { id: 'e018', name: 'Smith Machine Bench Press', muscle: 'Chest', category: 'Compound', equipment: 'Smith Machine' },
  { id: 'e019', name: 'Svend Press', muscle: 'Chest', category: 'Isolation', equipment: 'Plate' },
  { id: 'e020', name: 'Chest Squeeze Push-Up', muscle: 'Chest', category: 'Isolation', equipment: 'Bodyweight' },

  // BACK
  { id: 'e021', name: 'Barbell Deadlift', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e022', name: 'Romanian Deadlift', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e023', name: 'Barbell Row', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e024', name: 'T-Bar Row', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e025', name: 'Pendlay Row', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e026', name: 'Pull-Up', muscle: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e027', name: 'Chin-Up', muscle: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e028', name: 'Wide-Grip Pull-Up', muscle: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e029', name: 'Neutral-Grip Pull-Up', muscle: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e030', name: 'Lat Pulldown', muscle: 'Back', category: 'Compound', equipment: 'Cable' },
  { id: 'e031', name: 'Wide-Grip Lat Pulldown', muscle: 'Back', category: 'Compound', equipment: 'Cable' },
  { id: 'e032', name: 'Close-Grip Lat Pulldown', muscle: 'Back', category: 'Compound', equipment: 'Cable' },
  { id: 'e033', name: 'Single-Arm Dumbbell Row', muscle: 'Back', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e034', name: 'Dumbbell Pullover', muscle: 'Back', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e035', name: 'Seated Cable Row', muscle: 'Back', category: 'Compound', equipment: 'Cable' },
  { id: 'e036', name: 'Face Pull', muscle: 'Back', category: 'Isolation', equipment: 'Cable' },
  { id: 'e037', name: 'Straight-Arm Pulldown', muscle: 'Back', category: 'Isolation', equipment: 'Cable' },
  { id: 'e038', name: 'Machine Row', muscle: 'Back', category: 'Compound', equipment: 'Machine' },
  { id: 'e039', name: 'Hyperextension', muscle: 'Back', category: 'Isolation', equipment: 'Machine' },
  { id: 'e040', name: 'Good Morning', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e041', name: 'Rack Pull', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e042', name: 'Inverted Row', muscle: 'Back', category: 'Compound', equipment: 'Bodyweight' },

  // SHOULDERS
  { id: 'e043', name: 'Overhead Press (OHP)', muscle: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { id: 'e044', name: 'Seated Dumbbell Press', muscle: 'Shoulders', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e045', name: 'Standing Dumbbell Press', muscle: 'Shoulders', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e046', name: 'Arnold Press', muscle: 'Shoulders', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e047', name: 'Lateral Raise', muscle: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e048', name: 'Cable Lateral Raise', muscle: 'Shoulders', category: 'Isolation', equipment: 'Cable' },
  { id: 'e049', name: 'Front Raise', muscle: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e050', name: 'Rear Delt Fly', muscle: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e051', name: 'Reverse Pec Deck', muscle: 'Shoulders', category: 'Isolation', equipment: 'Machine' },
  { id: 'e052', name: 'Upright Row', muscle: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { id: 'e053', name: 'Barbell Shrug', muscle: 'Shoulders', category: 'Isolation', equipment: 'Barbell' },
  { id: 'e054', name: 'Dumbbell Shrug', muscle: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e055', name: 'Machine Shoulder Press', muscle: 'Shoulders', category: 'Compound', equipment: 'Machine' },
  { id: 'e056', name: 'Push Press', muscle: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { id: 'e057', name: 'Cable Front Raise', muscle: 'Shoulders', category: 'Isolation', equipment: 'Cable' },
  { id: 'e058', name: 'Band Pull-Apart', muscle: 'Shoulders', category: 'Isolation', equipment: 'Band' },

  // BICEPS
  { id: 'e059', name: 'Barbell Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Barbell' },
  { id: 'e060', name: 'EZ-Bar Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'EZ Bar' },
  { id: 'e061', name: 'Dumbbell Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e062', name: 'Hammer Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e063', name: 'Incline Dumbbell Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e064', name: 'Concentration Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e065', name: 'Preacher Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Barbell' },
  { id: 'e066', name: 'Cable Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Cable' },
  { id: 'e067', name: 'Rope Hammer Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Cable' },
  { id: 'e068', name: 'Machine Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Machine' },
  { id: 'e069', name: 'Cross-Body Hammer Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e070', name: 'Reverse Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Barbell' },
  { id: 'e071', name: 'Spider Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },

  // TRICEPS
  { id: 'e072', name: 'Close-Grip Bench Press', muscle: 'Triceps', category: 'Compound', equipment: 'Barbell' },
  { id: 'e073', name: 'Tricep Dip', muscle: 'Triceps', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e074', name: 'Skull Crusher', muscle: 'Triceps', category: 'Isolation', equipment: 'Barbell' },
  { id: 'e075', name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', category: 'Isolation', equipment: 'EZ Bar' },
  { id: 'e076', name: 'Overhead Tricep Extension', muscle: 'Triceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e077', name: 'Tricep Pushdown (Rope)', muscle: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { id: 'e078', name: 'Tricep Pushdown (Bar)', muscle: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { id: 'e079', name: 'Overhead Cable Extension', muscle: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { id: 'e080', name: 'Kickback', muscle: 'Triceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e081', name: 'Diamond Push-Up', muscle: 'Triceps', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e082', name: 'JM Press', muscle: 'Triceps', category: 'Compound', equipment: 'Barbell' },
  { id: 'e083', name: 'Machine Tricep Extension', muscle: 'Triceps', category: 'Isolation', equipment: 'Machine' },

  // LEGS - QUADS
  { id: 'e084', name: 'Barbell Back Squat', muscle: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { id: 'e085', name: 'Front Squat', muscle: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { id: 'e086', name: 'Goblet Squat', muscle: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e087', name: 'Hack Squat', muscle: 'Quads', category: 'Compound', equipment: 'Machine' },
  { id: 'e088', name: 'Leg Press', muscle: 'Quads', category: 'Compound', equipment: 'Machine' },
  { id: 'e089', name: 'Leg Extension', muscle: 'Quads', category: 'Isolation', equipment: 'Machine' },
  { id: 'e090', name: 'Bulgarian Split Squat', muscle: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e091', name: 'Walking Lunge', muscle: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e092', name: 'Reverse Lunge', muscle: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e093', name: 'Step-Up', muscle: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e094', name: 'Smith Machine Squat', muscle: 'Quads', category: 'Compound', equipment: 'Smith Machine' },
  { id: 'e095', name: 'Pistol Squat', muscle: 'Quads', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e096', name: 'Sissy Squat', muscle: 'Quads', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e097', name: 'Wall Sit', muscle: 'Quads', category: 'Isolation', equipment: 'Bodyweight' },

  // LEGS - HAMSTRINGS
  { id: 'e098', name: 'Romanian Deadlift', muscle: 'Hamstrings', category: 'Compound', equipment: 'Barbell' },
  { id: 'e099', name: 'Lying Leg Curl', muscle: 'Hamstrings', category: 'Isolation', equipment: 'Machine' },
  { id: 'e100', name: 'Seated Leg Curl', muscle: 'Hamstrings', category: 'Isolation', equipment: 'Machine' },
  { id: 'e101', name: 'Standing Leg Curl', muscle: 'Hamstrings', category: 'Isolation', equipment: 'Machine' },
  { id: 'e102', name: 'Nordic Curl', muscle: 'Hamstrings', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e103', name: 'Sumo Deadlift', muscle: 'Hamstrings', category: 'Compound', equipment: 'Barbell' },
  { id: 'e104', name: 'Single-Leg RDL', muscle: 'Hamstrings', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e105', name: 'Glute-Ham Raise', muscle: 'Hamstrings', category: 'Compound', equipment: 'Machine' },
  { id: 'e106', name: 'Good Morning', muscle: 'Hamstrings', category: 'Compound', equipment: 'Barbell' },

  // LEGS - GLUTES
  { id: 'e107', name: 'Hip Thrust', muscle: 'Glutes', category: 'Isolation', equipment: 'Barbell' },
  { id: 'e108', name: 'Dumbbell Hip Thrust', muscle: 'Glutes', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e109', name: 'Glute Bridge', muscle: 'Glutes', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e110', name: 'Cable Kickback', muscle: 'Glutes', category: 'Isolation', equipment: 'Cable' },
  { id: 'e111', name: 'Donkey Kickback', muscle: 'Glutes', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e112', name: 'Abduction Machine', muscle: 'Glutes', category: 'Isolation', equipment: 'Machine' },
  { id: 'e113', name: 'Clamshell', muscle: 'Glutes', category: 'Isolation', equipment: 'Band' },
  { id: 'e114', name: 'Frog Pump', muscle: 'Glutes', category: 'Isolation', equipment: 'Bodyweight' },

  // CALVES
  { id: 'e115', name: 'Standing Calf Raise', muscle: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { id: 'e116', name: 'Seated Calf Raise', muscle: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { id: 'e117', name: 'Donkey Calf Raise', muscle: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { id: 'e118', name: 'Single-Leg Calf Raise', muscle: 'Calves', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e119', name: 'Leg Press Calf Raise', muscle: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { id: 'e120', name: 'Box Jump (calf focus)', muscle: 'Calves', category: 'Compound', equipment: 'Bodyweight' },

  // ABS / CORE
  { id: 'e121', name: 'Crunch', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e122', name: 'Sit-Up', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e123', name: 'Leg Raise', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e124', name: 'Hanging Leg Raise', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e125', name: 'Hanging Knee Raise', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e126', name: 'Cable Crunch', muscle: 'Abs', category: 'Isolation', equipment: 'Cable' },
  { id: 'e127', name: 'Plank', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e128', name: 'Side Plank', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e129', name: 'Ab Wheel Rollout', muscle: 'Abs', category: 'Compound', equipment: 'Ab Wheel' },
  { id: 'e130', name: 'Bicycle Crunch', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e131', name: 'Russian Twist', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e132', name: 'Mountain Climber', muscle: 'Abs', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e133', name: 'V-Up', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e134', name: 'Dragon Flag', muscle: 'Abs', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e135', name: 'Pallof Press', muscle: 'Abs', category: 'Isolation', equipment: 'Cable' },
  { id: 'e136', name: 'Dead Bug', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e137', name: 'Windshield Wiper', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e138', name: 'Hollow Body Hold', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e139', name: 'Toes-to-Bar', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e140', name: 'Decline Crunch', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },

  // FOREARMS
  { id: 'e141', name: 'Wrist Curl', muscle: 'Forearms', category: 'Isolation', equipment: 'Barbell' },
  { id: 'e142', name: 'Reverse Wrist Curl', muscle: 'Forearms', category: 'Isolation', equipment: 'Barbell' },
  { id: 'e143', name: 'Farmer Carry', muscle: 'Forearms', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e144', name: 'Plate Pinch', muscle: 'Forearms', category: 'Isolation', equipment: 'Plate' },
  { id: 'e145', name: 'Dead Hang', muscle: 'Forearms', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e146', name: 'Towel Pull-Up', muscle: 'Forearms', category: 'Compound', equipment: 'Bodyweight' },

  // CARDIO / CONDITIONING
  { id: 'e147', name: 'Treadmill Run', muscle: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { id: 'e148', name: 'Elliptical', muscle: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { id: 'e149', name: 'Stairmaster', muscle: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { id: 'e150', name: 'Stationary Bike', muscle: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { id: 'e151', name: 'Jump Rope', muscle: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { id: 'e152', name: 'Box Jump', muscle: 'Cardio', category: 'Cardio', equipment: 'Bodyweight' },
  { id: 'e153', name: 'Burpee', muscle: 'Cardio', category: 'Cardio', equipment: 'Bodyweight' },
  { id: 'e154', name: 'Battle Ropes', muscle: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { id: 'e155', name: 'Sled Push', muscle: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { id: 'e156', name: 'Rowing Machine', muscle: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { id: 'e157', name: 'Assault Bike', muscle: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { id: 'e158', name: 'Swimming', muscle: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { id: 'e159', name: 'HIIT Sprint', muscle: 'Cardio', category: 'Cardio', equipment: 'Bodyweight' },
  { id: 'e160', name: 'Incline Walk', muscle: 'Cardio', category: 'Cardio', equipment: 'Machine' },

  // FULL BODY / FUNCTIONAL
  { id: 'e161', name: 'Power Clean', muscle: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { id: 'e162', name: 'Hang Clean', muscle: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { id: 'e163', name: 'Clean and Jerk', muscle: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { id: 'e164', name: 'Snatch', muscle: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { id: 'e165', name: 'Kettlebell Swing', muscle: 'Full Body', category: 'Compound', equipment: 'Kettlebell' },
  { id: 'e166', name: 'Kettlebell Clean', muscle: 'Full Body', category: 'Compound', equipment: 'Kettlebell' },
  { id: 'e167', name: 'Kettlebell Snatch', muscle: 'Full Body', category: 'Compound', equipment: 'Kettlebell' },
  { id: 'e168', name: 'Thruster', muscle: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { id: 'e169', name: 'Turkish Get-Up', muscle: 'Full Body', category: 'Compound', equipment: 'Kettlebell' },
  { id: 'e170', name: 'Bear Crawl', muscle: 'Full Body', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e171', name: 'Man Maker', muscle: 'Full Body', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e172', name: 'Barbell Complex', muscle: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { id: 'e173', name: 'Medicine Ball Slam', muscle: 'Full Body', category: 'Compound', equipment: 'Other' },
  { id: 'e174', name: 'Sandbag Carry', muscle: 'Full Body', category: 'Compound', equipment: 'Other' },

  // ADDITIONAL CHEST
  { id: 'e175', name: 'Loaded Stretch Fly', muscle: 'Chest', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e176', name: 'Deficit Push-Up', muscle: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e177', name: 'Clap Push-Up', muscle: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { id: 'e178', name: 'Cable Pullover', muscle: 'Chest', category: 'Isolation', equipment: 'Cable' },
  // ADDITIONAL BACK
  { id: 'e179', name: 'Meadows Row', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e180', name: 'Kroc Row', muscle: 'Back', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e181', name: 'Chest-Supported Row', muscle: 'Back', category: 'Compound', equipment: 'Dumbbell' },
  { id: 'e182', name: 'Seal Row', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  { id: 'e183', name: 'Yates Row', muscle: 'Back', category: 'Compound', equipment: 'Barbell' },
  // ADDITIONAL SHOULDERS
  { id: 'e184', name: 'Leaning Lateral Raise', muscle: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e185', name: 'W-Raise', muscle: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e186', name: 'Landmine Press', muscle: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  // ADDITIONAL LEGS
  { id: 'e187', name: 'Leg Press (Single Leg)', muscle: 'Quads', category: 'Compound', equipment: 'Machine' },
  { id: 'e188', name: 'Pause Squat', muscle: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { id: 'e189', name: 'Box Squat', muscle: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { id: 'e190', name: 'Safety Bar Squat', muscle: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { id: 'e191', name: 'Cable Pull-Through', muscle: 'Glutes', category: 'Isolation', equipment: 'Cable' },
  { id: 'e192', name: 'Single-Leg Hip Thrust', muscle: 'Glutes', category: 'Isolation', equipment: 'Bodyweight' },
  // ADDITIONAL ABS
  { id: 'e193', name: 'L-Sit', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  { id: 'e194', name: 'Cable Wood Chop', muscle: 'Abs', category: 'Compound', equipment: 'Cable' },
  { id: 'e195', name: 'Oblique Crunch', muscle: 'Abs', category: 'Isolation', equipment: 'Bodyweight' },
  // ADDITIONAL BICEPS
  { id: 'e196', name: 'Bayesian Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Cable' },
  { id: 'e197', name: 'Zottman Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e198', name: 'Waiter Curl', muscle: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  // ADDITIONAL TRICEPS
  { id: 'e199', name: 'Tate Press', muscle: 'Triceps', category: 'Isolation', equipment: 'Dumbbell' },
  { id: 'e200', name: 'Rolling Tricep Extension', muscle: 'Triceps', category: 'Isolation', equipment: 'Dumbbell' },
];

const MUSCLES = ['All', ...new Set(EXERCISES.map(e => e.muscle))].sort((a,b) => a==='All'?-1:b==='All'?1:a.localeCompare(b));
const EQUIPMENT_LIST = ['All', ...new Set(EXERCISES.map(e => e.equipment))].sort((a,b) => a==='All'?-1:b==='All'?1:a.localeCompare(b));
